# Generated by Django 3.1.6 on 2021-06-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='')),
                ('Age', models.TextField(default='')),
                ('Gender', models.TextField(choices=[('F', 'Female'), ('M', 'Male')], default='')),
                ('Address', models.TextField(default='')),
                ('Birthdate', models.DateTimeField(default='')),
                ('Contact_No', models.TextField(default='')),
                ('Emailaddress', models.TextField(default='')),
                ('Company_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Days', models.TextField(default='')),
                ('Rate', models.TextField(default='')),
                ('Deduction', models.TextField(default='')),
                ('Status', models.TextField(default='')),
                ('Date_time', models.DateTimeField(default='')),
                ('employee_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.employee_info')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeereport', models.TextField(default='')),
                ('Employee_comment', models.TextField(default='')),
                ('Company_rating', models.TextField(default='')),
                ('Empreport_date', models.DateTimeField(default='')),
                ('employee_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.employee_info')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('Operations', 'operations'), ('Quality Assurance', 'QA'), ('Human Resource', 'HR'), ('Administration', 'Admin'), ('Training', 'training')], default='', max_length=20)),
                ('Dep_status', models.TextField(default='')),
                ('Employee_position', models.TextField(default='')),
                ('employee_info', models.ManyToManyField(default=None, to='CEList.Employee_info')),
            ],
        ),
        migrations.CreateModel(
            name='Company_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyreport', models.TextField(default='')),
                ('Company_comment', models.TextField(default='')),
                ('Comreport_date', models.DateTimeField(default='')),
                ('employee_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.employee_salary')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_branch', models.CharField(choices=[('Cavite', 'cavite'), ('Manila', 'manila'), ('Caloocan', 'caloocan'), ('Taguig', 'taguig')], default='', max_length=20)),
                ('Company_address', models.TextField(default='')),
                ('employee_info', models.ManyToManyField(default=None, to='CEList.Employee_info')),
            ],
        ),
    ]
