# Generated by Django 3.1.6 on 2021-05-21 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.TextField(default='')),
                ('venue', models.TextField(default='')),
                ('date_time', models.DateTimeField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Customers_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers_name', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('book_date', models.DateTimeField(default='')),
                ('contact_number', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(default='')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_names', models.TextField(default='')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.TextField(default='')),
                ('booking', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customers_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.customers_profile'),
        ),
        migrations.CreateModel(
            name='Adds_On',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionals', models.TextField(default='')),
                ('booking', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.booking')),
            ],
        ),
    ]
