# Generated by Django 3.1.6 on 2021-06-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Employee_position',
            new_name='Position',
        ),
    ]
