# Generated by Django 3.1.6 on 2021-05-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0002_item_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='text',
            new_name='nAddress',
        ),
        migrations.AddField(
            model_name='item',
            name='nBreed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='nDay',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='nname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='npet',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='CEList.list'),
        ),
    ]
