# Generated by Django 3.1.6 on 2021-06-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0002_auto_20210616_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_info',
            name='Birthdate',
        ),
    ]
