# Generated by Django 3.1.6 on 2021-05-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0003_auto_20210501_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nBreed',
            new_name='ndate',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nDay',
            new_name='nitem',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='npet',
            new_name='nprice',
        ),
    ]
