# Generated by Django 3.1.6 on 2021-06-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0005_auto_20210623_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='employee_info',
            new_name='employee_branch',
        ),
        migrations.RenameField(
            model_name='company_report',
            old_name='employee_info',
            new_name='employee_comrep',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='employee_info',
            new_name='employee_dep',
        ),
        migrations.RenameField(
            model_name='employee_report',
            old_name='employee_info',
            new_name='employee_emrep',
        ),
    ]
