# Generated by Django 3.1.6 on 2021-06-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0006_auto_20210624_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_report',
            name='employee_comrep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.employee_info'),
        ),
    ]
