# Generated by Django 3.1.6 on 2021-06-25 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0007_auto_20210624_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Department',
            field=models.CharField(choices=[('Operations', 'operations'), ('Quality Assurance', 'QA'), ('Human Resource', 'HR'), ('Administration', 'Admin'), ('Training', 'training')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='Position',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='employee_branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='employee_branch',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='CEList.employee_info'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
