# Generated by Django 3.1.6 on 2021-06-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0008_auto_20210625_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='Company_address',
        ),
    ]
