# Generated by Django 3.1.6 on 2021-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEList', '0010_remove_employee_report_company_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_report',
            name='Company_rating',
            field=models.TextField(default=''),
        ),
    ]
